# Generated by Django 4.2.5 on 2023-09-25 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_offer_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
