# Generated by Django 4.2.5 on 2023-10-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_rfq_srv_rfq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rfq_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.rfq'),
        ),
    ]
