# Generated by Django 4.2.5 on 2023-10-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_alter_offer_rfq_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='rfq_no',
            new_name='rfq',
        ),
    ]
