# Generated by Django 4.2.5 on 2023-10-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_rename_rfq_no_offer_rfq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='rfq_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
