# Generated by Django 4.2.5 on 2023-10-02 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_rfq_rfq_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
