# Generated by Django 4.2.5 on 2023-10-02 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_customer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
