# Generated by Django 4.2.5 on 2023-10-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_part_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfq',
            old_name='date',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='rfq',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='rfq_mail',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('in progress', 'In Progress'), ('n/a', 'N/A')], default='in progress', max_length=25),
        ),
    ]
