# Generated by Django 4.2.5 on 2023-10-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0017_alter_rfq_rfq_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
