# Generated by Django 4.2.5 on 2023-10-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_alter_part_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kum_dokum', models.FloatField(blank=True, default=0, null=True)),
                ('kokil_dokum', models.FloatField(blank=True, default=0, null=True)),
                ('enjeksiyon_dokum', models.FloatField(blank=True, default=0, null=True)),
                ('soguk_maca', models.FloatField(blank=True, default=0, null=True)),
                ('takalama', models.FloatField(blank=True, default=0, null=True)),
                ('testere', models.FloatField(blank=True, default=0, null=True)),
                ('zimpara', models.FloatField(blank=True, default=0, null=True)),
                ('tesviye', models.FloatField(blank=True, default=0, null=True)),
                ('kumlama', models.FloatField(blank=True, default=0, null=True)),
                ('test_sizdirmazlik', models.FloatField(blank=True, default=0, null=True)),
                ('test_temizleme', models.FloatField(blank=True, default=0, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.offer')),
            ],
        ),
    ]
