# Generated by Django 4.2.5 on 2023-10-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0019_offerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='boya',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='cnc_dik_isleme',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='cnc_yatay_isleme',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='dis_isleme',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='dokum_tipi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='emprenye',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='heli_coil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='isil_islem_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='isil_islem_sarj',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='kalip_fiyati',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='kalip_goz_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='kalip_omru_baski_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='kaplama',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='maca_agirligi_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='maca_goz_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='maca_tipi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='malzeme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='min_siparis_adedi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='montaj_kaynak',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='montaj_parca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='mukavemet_testi',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='nakliye_maliyeti',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='paketleme',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='para_birimi',
            field=models.CharField(choices=[('EUR', 'Euro'), ('TL', 'Türk Lirası'), ('USD', 'Dollar')], default='TL', max_length=25),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='parca_agirligi_kg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='parca_fiyati',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='sicak_maca',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='teslim_turu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='torna',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='vibrasyon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='x_ray_testi',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='yillik_adet',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
